//
//  DetailRouter.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 26/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol DetailRoutingLogic { }

protocol DetailDataPassing {
    var dataStore: DetailDataStore? { get }
}

class DetailRouter<T: Item>: NSObject, DetailRoutingLogic, DetailDataPassing {
    weak var viewController: DetailController<T>?
    var dataStore: DetailDataStore?
    
}
