//
//  DoorsInteractor.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 24/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DoorsBusinessLogic
{
  func doSomething(request: Doors.Something.Request)
}

protocol DoorsDataStore
{
  //var name: String { get set }
}

class DoorsInteractor: DoorsBusinessLogic, DoorsDataStore
{
  var presenter: DoorsPresentationLogic?
  var worker: DoorsWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: Doors.Something.Request)
  {
    worker = DoorsWorker()
    worker?.doSomeWork()
    
    let response = Doors.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
