//
//  DoorsPresenter.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 24/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DoorsPresentationLogic
{
  func presentSomething(response: Doors.Something.Response)
}

class DoorsPresenter: DoorsPresentationLogic
{
  weak var viewController: DoorsDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Doors.Something.Response)
  {
    let viewModel = Doors.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
