//
//  UnlockPresenterTests.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 21/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheCloudLock
import XCTest

class UnlockPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: UnlockPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupUnlockPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupUnlockPresenter()
  {
    sut = UnlockPresenter()
  }
  
  // MARK: Test doubles
  
  class UnlockDisplayLogicSpy: UnlockDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: Unlock.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = UnlockDisplayLogicSpy()
    sut.viewController = spy
    let response = Unlock.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
