//
//  UnlockInteractorTests.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 21/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import TheCloudLock
import XCTest

class UnlockInteractorTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: UnlockInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupUnlockInteractor()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupUnlockInteractor()
  {
    sut = UnlockInteractor()
  }
  
  // MARK: Test doubles
  
  class UnlockPresentationLogicSpy: UnlockPresentationLogic
  {
    var presentSomethingCalled = false
    
    func presentSomething(response: Unlock.Something.Response)
    {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething()
  {
    // Given
    let spy = UnlockPresentationLogicSpy()
    sut.presenter = spy
    let request = Unlock.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
