//
//  ListModels.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 24/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List {
    // MARK: - Use cases
    
    enum FetchItems {
        struct Request {
            var row: Int?
            var name: String?
        }
        struct Response {
            let items: [Item]
            var error: CloudLockError?
        }
        struct ViewModel {
            var items: [DisplayedItem]
            let resultMessage: String
            
            struct DisplayedItem: Item {
                var id: String
                var name: String
            }
        }
    }
    
    enum FetchItemCredentials {
        struct Request {
            var id: String
            var name: String
        }
        struct Response {
            var error: CloudLockError?
        }
        struct ViewModel {
            let resultMessage: String
        }
    }
    
    enum State {
        case loading
        case ready
    }
}

typealias DisplayedItem = List.FetchItems.ViewModel.DisplayedItem
