//
//  UnlockInteractor.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 18/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol UnlockBusinessLogic {
    func doSomething(request: Unlock.Something.Request)
}

protocol UnlockDataStore {
    //var name: String { get set }
}

class UnlockInteractor: UnlockBusinessLogic, UnlockDataStore {
    var presenter: UnlockPresentationLogic?
    var worker: UnlockWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: Unlock.Something.Request) {
        worker = UnlockWorker()
        worker?.doSomeWork()
        
        let response = Unlock.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
