//
//  UnlockWorker.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 18/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum UnlockError: Error {
    case notFound
    case notAuthorized
}

class UnlockWorker {
    
    func findDoors(request: Unlock.FetchDoors.Request,
                   completion: @escaping (Result<Unlock.FetchDoors.Response, UnlockError>) -> Void) {
        DispatchQueue.main.asyncAfter(deadline: .now() + 2) {
            completion(.success(Unlock.FetchDoors.Response(doorID: 1,
                                                           name: "Main entrance",
                                                           image: "livingroom")))
        }
    }
}
