//
//  UnlockModels.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 18/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Unlock {
    // MARK: Use cases
    enum FetchDoors {
        
        struct Request {}
        
        struct Response {
            let doors: [Doors]?
            let error: CloudLockError?
        }
        
        struct ViewModel {
            let state: State
            let resultMessage: String
            let items: [Item]
            
            struct Item {
                let doorImage: UIImage?
                let doorName: String
            }
        }
    }
    
    enum UnlockDoor {
        struct Request {}
        
        struct Response {
            let error: CloudLockError?
        }
        
        struct ViewModel {
            let state: State
            let resultMessage: String
        }
    }
    
    enum State {
        case loading(_ message: String?)
        case fetchDoorsError
        case fetchDoorsSuccess
        case unlockDoorSucess
        case unlockDoorError
        case unlockDoorAuthError
    }
}

extension Unlock.State: Equatable {}
