//
//  UnlockRouter.swift
//  TheCloudLock
//
//  Created by Matheus Vasconcelos on 18/01/20.
//  Copyright (c) 2020 AppCompany. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol UnlockRoutingLogic { }

protocol UnlockDataPassing {
  var dataStore: UnlockDataStore? { get }
}

class UnlockRouter: NSObject, UnlockRoutingLogic, UnlockDataPassing {
  weak var viewController: UIViewController?
  var dataStore: UnlockDataStore?
}
